### ISSUE TITLE
Package Migration Status

### ISSUE THREAD

**Issue by AdmiringWorm** [chocolatey/chocolatey-coreteampackages#707]
Instead of having the list of packages that haven't yet been migrated to AU (or removed/moved to manual, etc.) on the wiki, I'm adding it here.
Some of these have been moved to the manual directory, but is missing checksums.

1. [ ] [libreoffice-help](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/libreoffice-help) *Should be deprecated in favor of upstream naming change `libreoffice-{still,fresh}-help`* *- PR Submitted #528*
1. [X] [ontopreplica](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/ontopreplica)
1. [x] [pspp](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/pspp)
1. [x] [PandaFreeAntivirus](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/pandafreeantivirus)
1. [x] [rukerneltool](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/rukerneltool)
1. [x] [scite4autohotkey](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/manual/scite4autohotkey) *PR Submitted #708*
1. [x] [scribus](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/scribus) *PR Submitted #709*
1. [x] [secret-maryo-chronicles](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/secret-maryo-chronicles)
1. [x] [sidesync](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/sidesync)
1. [x] [sweet-home-3d](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/sweet-home-3d)
1. [x] [testdisk-photorec](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/testdisk-photorec)
1. [x] [texmaker](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/texmaker)
1. [x] [tor-browser](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/tor-browser) *- PR Submitted #508*
1. [x] [universal-usb-installer](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/universal-usb-installer)
1. [x] [virtualdub](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/virtualdub) *PR Submitted #711*
1. [x] [vp8-vfw](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/vp8-vfw)
1. [x] [x2go](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/x2go)
1. [x] [x-moto](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/x-moto)
1. [x] [xpdf-utils](https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/xpdf-utils)

**Comment by majkinetor** [comment]
I will remove `rukerneltool` from this repository because of package priorities. It doesn't have english localization (english lang. should be mandatory in the guidelines, I will add it), its low on users and it isn't obvious what it does on choco. Don't know about unlisting it but chocolatey user should be removed from the maintainers.

**Comment by majkinetor** [comment]
Lets discuss Panda.

Since there is only commercial package, almost no users and obvious no desire to maintain it, I would remove it from here and remove chocolatey user as maintainer.

**Comment by AdmiringWorm** [comment]
I don't mind removing them both TBH, but if they are to be removed then we should add both those packages as a RFM over at https://github.com/chocolatey/chocolatey-package-requests/issues

**Comment by majkinetor** [comment]
Ok,  lets do that.

**Comment by AdmiringWorm** [comment]
I've opened RFM for both the [rukerneltool](https://github.com/chocolatey/chocolatey-package-requests/issues/144) and the [PandaFreeAntivirus](https://github.com/chocolatey/chocolatey-package-requests/issues/145) packages.

I think we should keep the packages in this repo until someone have picked it up though (although I linked to specific commits)

**Comment by majkinetor** [comment]
OK, I just removed ketarin jobs until then.

**Comment by majkinetor** [comment]
Closing this as libreoffice-help has its own issue.

This finalizes ketarin packages on this repository. Congratz to all :)

/cc @ferventcoder @gep13

**Comment by gep13** [comment]
@majkinetor this is amazing news!  Well done to everyone!

Can I switch off the ketarin machine now?

**Comment by AdmiringWorm** [comment]
@gep13 yes you can, the libreoffice-help was removed from ketarin previously since it only kept pushing non-working versions of the package

**Comment by gep13** [comment]
@AdmiringWorm sweet.  I will get that shut down over the weekend.

Again, this is great news!  Well done everyone!
